name: Feature request
description: Suggest a new idea or improvement
title: "[Feature]: "
labels: [enhancement]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please check for similar requests before submitting a new one.

  - type: textarea
    id: problem
    attributes:
      label: Related Problem
      description: Describe the problem this feature would solve.
      placeholder: Why do you need this feature?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed changes or feature.
      placeholder: Explain your idea in detail.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered other solutions?
      placeholder: Describe any alternative approaches.
    validations:
      required: false